import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Artzeker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Purchase an Artzeker Plan</h1>
        <button>
          <Link href="/">
            <a>Back Home</a>
          </Link>
        </button>
      </main>
    </div>
  );
}
